apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-c
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-c
  minReplicas: {{ .Values.serviceC.replicas | default 1 }}
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70