apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
