apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-a
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-a
  minReplicas: {{ .Values.serviceA.replicas | default 2 }}
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
