# Add this at the top level of your values.yaml
skipIngress: false

frontend:
  image: ashokvsetty/3-tier-microservices-frontend:latest
  imagePullPolicy: Always

serviceA:
  image: ashokvsetty/3-tier-microservices-service-a:latest
  imagePullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: "0.5"
      memory: "256Mi"
    requests:
      cpu: "0.1"
      memory: "128Mi"

serviceB:
  image: ashokvsetty/3-tier-microservices-service-b:latest
  imagePullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: "0.5"
      memory: "256Mi"
    requests:
      cpu: "0.1"
      memory: "128Mi"

serviceC:
  image: ashokvsetty/3-tier-microservices-service-c:latest
  imagePullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: "0.5"
      memory: "256Mi"
    requests:
      cpu: "0.1"
      memory: "128Mi"
